/*
 * TrackControlPanel.java
 *
 * Created on June 14, 2007, 4:57 PM
 */

/*
 * Copyright (C) 2009, Edmundo Albuquerque de Souza e Silva.
 *
 * This file may be distributed under the terms of the Q Public License
 * as defined by Trolltech AS of Norway and appearing in the file
 * LICENSE.QPL included in the packaging of this file.
 *
 * THIS FILE IS PROVIDED AS IS WITH NO WARRANTY OF ANY KIND, INCLUDING
 * THE WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL,
 * INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING
 * FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
 * NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
 * WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 *
 */

package net.sf.fmj.ui.wizards;

/**
 *
 * 
 */
public class TrackControlPanel extends javax.swing.JPanel {
    
    /** Creates new form TrackControlPanel */
    public TrackControlPanel() {
        initComponents();
    }
    
    
    private AudioFormatPanel audioFormatPanel;
    public void setAudioFormatPanel(AudioFormatPanel audioFormatPanel)
    {
    	this.audioFormatPanel = audioFormatPanel;
    	panelFormat.add(audioFormatPanel);
    }
    
//    public javax.swing.JPanel getPanelFormat()
//	{
//		return panelFormat;
//	}



	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        checkBoxEnableTrack = new javax.swing.JCheckBox();
        panelFormat = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        checkBoxEnableTrack.setText("Enable track");
        checkBoxEnableTrack.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        checkBoxEnableTrack.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(checkBoxEnableTrack, gridBagConstraints);

        panelFormat.setLayout(new java.awt.GridBagLayout());

        panelFormat.setBorder(javax.swing.BorderFactory.createTitledBorder("Format"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(panelFormat, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBoxEnableTrack;
    private javax.swing.JPanel panelFormat;
    // End of variables declaration//GEN-END:variables
	public javax.swing.JCheckBox getCheckBoxEnableTrack()
	{
		return checkBoxEnableTrack;
	}

	public AudioFormatPanel getAudioFormatPanel()
	{
		return audioFormatPanel;
	}
    
}
